version: '3.2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mcm@123
      POSTGRES_DB: mcm
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6378:6379

  convert-service:
    image: thecodingmachine/gotenberg:6
    ports:
      - 3001:3000
  image-proxy-service:
    image: darthsim/imgproxy:latest
    ports:
      - 3002:8080
    env_file:
      - ../.env