// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package worker

import (
	"mcm-api/internal/core"
	"mcm-api/pkg/queue"
)

// Injectors from injector.go:

func InitializeWorker() *worker {
	config := core.ProvideConfig()
	client := core.ProvideRedis(config)
	queueQueue := queue.InitializeRedisQueue(config, client)
	workerWorker := newWorker(config, queueQueue)
	return workerWorker
}
