// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package document

import (
	"gorm.io/gorm"
)

// Injectors from inject.go:

func InjectService(db *gorm.DB) *Service {
	documentRepository := NewRepository(db)
	service := NewService(documentRepository)
	return service
}
