// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package internal

import (
	"mcm-api/internal/core"
	"mcm-api/internal/router"
	"mcm-api/pkg/document"
	"mcm-api/pkg/user"
)

import (
	_ "mcm-api/docs"
)

// Injectors from injector.go:

func InitializeServer() *Server {
	config := core.ProvideConfig()
	db := core.ProvideDB(config)
	repository := user.InitializeRepository(db)
	service := user.InitializeService(repository)
	userRouter := router.NewUserRouter(service)
	documentRepository := document.InitializeRepository(db)
	documentService := document.InitializeService(documentRepository)
	documentRouter := router.NewDocumentRouter(documentService)
	server := newServer(config, userRouter, documentRouter)
	return server
}
