// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package internal

import (
	"mcm-api/internal/core"
	"mcm-api/pkg/authz"
	"mcm-api/pkg/document"
	"mcm-api/pkg/startup"
	"mcm-api/pkg/user"
)

import (
	_ "mcm-api/docs"
)

// Injectors from injector.go:

func InitializeServer() *Server {
	config := core.ProvideConfig()
	db := core.ProvideDB(config)
	repository := user.InitializeRepository(db)
	enforcer := core.ProvideEnforcer(db)
	service := user.InitializeService(config, repository, enforcer)
	startupService := startup.InitializeStartUpService(service)
	authzService := authz.InitializeAuthService(config, service)
	handler := authz.NewAuthHandler(authzService)
	userHandler := user.NewUserHandler(config, service)
	documentRepository := document.InitializeRepository(db)
	documentService := document.InitializeService(documentRepository)
	documentHandler := document.NewDocumentHandler(documentService)
	server := newServer(config, startupService, handler, userHandler, documentHandler)
	return server
}
