// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package internal

import (
	"mcm-api/internal/core"
	"mcm-api/pkg/document"
	"mcm-api/pkg/user"
)

import (
	_ "mcm-api/docs"
)

// Injectors from injector.go:

func InitializeServer() *Server {
	config := core.ProvideConfig()
	db := core.ProvideDB(config)
	repository := user.InitializeRepository(db)
	service := user.InitializeService(repository)
	userHandler := user.NewUserHandler(service)
	documentRepository := document.InitializeRepository(db)
	documentService := document.InitializeService(documentRepository)
	documentHandler := document.NewDocumentHandler(documentService)
	server := newServer(config, userHandler, documentHandler)
	return server
}
